text_offset = 0xB5CB20
text_size = 0xAF0
text_address = 0x04001080
rom_file_path = "oot.us.rom_uncompressed.z64"
output_file_path = "rsp_oot/njpgdspMain.cpp"
output_function_name = "oot_njpgdspMain"
extra_indirect_branch_targets = []
